apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-image-repository.yaml
  - auth-service-image-repository.yaml
  - todo-service-image-repository.yaml
  - frontend-image-policy.yaml
  - auth-service-image-policy.yaml
  - todo-service-image-policy.yaml
  - image-update-automation.yaml
