namespace: todo-platform
images:
  frontend: ghcr.io/rajdeepmishra01/frontend:8 # {"$imagepolicy": "flux-system:frontend"}
  authService: ghcr.io/rajdeepmishra01/auth-service:7 # {"$imagepolicy": "flux-system:auth-service"}
  todoService: ghcr.io/rajdeepmishra01/todo-service:8 # {"$imagepolicy": "flux-system:todo-service"}
  postgres: postgres:16-alpine
postgres:
  database: todoapp
  user: postgres
  password: postgres
jwtSecret: secretkey
replicas:
  frontend: 2
  authService: 2
  todoService: 2
resources:
  frontend:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  authService:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  todoService:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  postgres:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
hpa:
  enabled: true
  frontend:
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 50
  authService:
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 50
  todoService:
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 50
