apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todo-platform
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: secretkey
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/todoapp
