grafana:
  enabled: true

prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    evaluationInterval: 15s

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true