apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: todo-platform
  namespace: flux-system
spec:
  interval: 1m
  releaseName: todo-platform
  targetNamespace: todo-platform
  chart:
    spec:
      chart: ./helm-charts/todo-platform
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    images:
      frontend: ghcr.io/rajdeepmishra01/frontend:22 # {"$imagepolicy": "flux-system:frontend"}
      authService: ghcr.io/rajdeepmishra01/auth-service:22 # {"$imagepolicy": "flux-system:auth-service"}
      todoService: ghcr.io/rajdeepmishra01/todo-service:22 # {"$imagepolicy": "flux-system:todo-service"}
    replicas:
      frontend: 3
      authService: 3
      todoService: 3
