apiVersion: v1
kind: ResourceQuota
metadata:
  name: todo-platform-quota
  namespace: todo-platform
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
